### PR TITLE
Changed the look of language selection page.

### PR DESCRIPTION
**Pull request by SouvikDuttaChowdhury**
I had to change the launcher icon names in android/app/src/main/res/mipmap from ic_launcher.png to launcher_icon.png since the code was not building and i was getting errors. Also the launcher icon is not the slavefreetrade logo, rather it is the default flutter icon. Should i make an issue about that? Also i was not able to get any survey while doing the work. I was building a fresh copy of code from the master branch. I thought that it could be my location that was affecting the availability of the survey. I used a VPN but that didn't help. So, i will probably make an issue about it and start working on that. That is it.

### CODE REVIEW

**Comment by MichaelKMalak** [comment]
@SouvikDuttaChowdhury is there an [open issue](https://github.com/slavefreetrade/libertas_people/issues) that this PR fixes?

**Comment by MichaelKMalak** [comment]
Regarding the launcher icon: you can run on the terminal the following `flutter pub run flutter_launcher_icons:main`

**Comment by SouvikDuttaChowdhury** [comment]
Yes this fixes #24

**Comment by MichaelKMalak** [comment]
@SouvikDuttaChowdhury 
The buttons look good, but they need a few adjustments in padding to look like all the following pages.

The language selection page: 
image

The next page: 
image

**Comment by SouvikDuttaChowdhury** [comment]
Alright I will change the padding.

**Pull request closed without merging**
